export const comunas = [
    "Comuna 1", "Comuna 2", "Comuna 3", "Comuna 4", "Comuna 5",
    "Comuna 6", "Comuna 7", "Comuna 8", "Comuna 9", "Comuna 10",
    "Comuna 11", "Comuna 12", "Comuna 13", "Comuna 14", "Comuna 15",
    "Comuna 16", "Comuna 17", "Comuna 18", "Comuna 19", "Comuna 20",
    "Comuna 21", "Comuna 22"
  ];



  export const barriosPorComuna = {
    "Comuna 1": [
      "Terrón Colorado",
      "Vista Hermosa",
      "Sector Patio Bonito",
      "Aguacatal"
    ],
    "Comuna 2": [
      "Santa Rita",
      "Santa Teresita",
      "Arboledas",
      "Normandía",
      "Juanambú",
      "Centenario",
      "Granada",
      "Versalles",
      "San Vicente",
      "Santa Mónica",
      "Prados del Norte",
      "La Flora",
      "La Campiña",
      "La Paz",
      "El Bosque",
      "Menga",
      "Ciudad Los Álamos",
      "Chipichape",
      "Brisas de los Álamos",
      "Urbanización La Merced",
      "Vipasa",
      "Urbanización La Flora",
      "Altos de Menga",
      "Sector Altos Normandía",
      "Senderos de la Flora"
    ],
    "Comuna 3": [
      "El Nacional",
      "El Peñón",
      "San Antonio",
      "San Cayetano",
      "Los Libertadores",
      "San Juan Bosco",
      "Santa Rosa",
      "La Merced",
      "San Pascual",
      "El Calvario",
      "San Pedro",
      "San Nicolás",
      "El Hoyo",
      "El Piloto",
      "Navarro - La Chanca"
    ],
    "Comuna 4": [
      "Jorge Isaacs",
      "Santander",
      "Porvenir",
      "Las Delicias",
      "Manzanares",
      "Salomia",
      "Fátima",
      "Sultana - Berlín - San Francisco",
      "Popular",
      "Ignacio Rengifo",
      "Guillermo Valencia",
      "La Isla",
      "Marco Fidel Suárez",
      "Evaristo García",
      "La Esmeralda",
      "Bolivariano",
      "Olaya Herrera",
      "Unidad Residencial Bueno Madrid",
      "Flora Industrial",
      "Calima",
      "Industria de Licores",
      "La Alianza"
    ],
    "Comuna 5": [
      "El Sena",
      "Los Andes",
      "Los Guayacanes",
      "Chiminangos Segunda Etapa",
      "Chiminangos Primera Etapa",
      "Metropolitano del Norte",
      "Los Parques - Barranquilla",
      "Villa del Sol",
      "Paseo de Los Almendros",
      "Los Andes B - La Riviera",
      "Torres de Comfandi",
      "Villa del Prado - El Guabito",
      "Brisas del Guabito"
    ],
    "Comuna 6": [
      "San Luis",
      "Jorge Eliecer Gaitán",
      "Paso del Comercio",
      "Los Alcázares",
      "Petecuy Primera Etapa",
      "Petecuy Segunda Etapa",
      "La Rivera Primera Etapa",
      "Los Guaduales",
      "Petecuy Tercera Etapa",
      "Ciudadela Floralia",
      "Fonaviemcali",
      "San Luis II",
      "Urbanización Calimio",
      "Sector Puente del Comercio"
    ],
    "Comuna 7": [
      "Alfonso López P. 1a. Etapa",
      "Alfonso López P. 2a. Etapa",
      "Alfonso López P. 3a. Etapa",
      "Puerto Nuevo",
      "Puerto Mallarino",
      "Urbanización El Ángel del Hogar",
      "Siete de Agosto",
      "Los Pinos",
      "San Marino",
      "Las Ceibas",
      "Base Aérea",
      "Parque de la Caña",
      "Fepicol",
      "Andrés Sanín"
    ],
    "Comuna 8": [
      "Primitivo Crespo",
      "Simón Bolívar",
      "Saavedra Galindo",
      "Uribe Uribe",
      "Santa Mónica Popular",
      "La Floresta",
      "Benjamín Herrera",
      "Municipal",
      "Industrial",
      "El Troncal",
      "Las Américas",
      "Atanasio Girardot",
      "Santa Fe",
      "Chapinero",
      "Villa Colombia",
      "El Trébol",
      "La Base",
      "Urbanización La Nueva Base"
    ],
    "Comuna 9": [
      "Alameda",
      "Bretaña",
      "Junín",
      "Guayaquil",
      "Aranjuez",
      "Manuel María Buenaventura",
      "Santa Mónica Belalcázar",
      "Belalcázar",
      "Sucre",
      "Barrio Obrero"
    ],
    "Comuna 10": [
      "El Dorado",
      "El Guabal",
      "La Libertad",
      "Santa Elena",
      "Las Acacias",
      "Santo Domingo",
      "Jorge Zawadsky",
      "Olímpico",
      "Cristóbal Colón",
      "La Selva",
      "Barrio Departamental",
      "Pasoancho",
      "Panamericano",
      "Colseguros Andes",
      "San Cristóbal",
      "Las Granjas",
      "San Judas Tadeo I Etapa",
      "San Judas Tadeo II Etapa"
    ],
    "Comuna 11": [
      "San Carlos",
      "Maracaibo",
      "La Independencia",
      "La Esperanza",
      "Urbanización Boyacá",
      "El Jardín",
      "La Fortaleza",
      "El Recuerdo",
      "Aguablanca",
      "El Prado",
      "Ciudad Modelo",
      "Prados de Oriente",
      "Los Sauces",
      "Villa del Sur",
      "José Holguín Garcés",
      "León XIII",
      "José María Córdoba",
      "San Pedro Claver",
      "Los Conquistadores",
      "La Gran Colombia",
      "San Benito",
      "Primavera"
    ],
    "Comuna 12": [
      "Villanueva",
      "Asturias",
      "Eduardo Santos",
      "Alfonso Barberena A.",
      "El Paraíso",
      "Fenalco Kennedy",
      "Nueva Floresta",
      "Julio Rincón",
      "Doce de Octubre",
      "El Rodeo",
      "Sindical",
      "Bello Horizonte"
    ],
    "Comuna 13": [
      "Horizontes I",
      "Horizontes II",
      "Urbanización El Lagito",
      "Altos de Santa Elena",
      "Ulpiano Lloreda",
      "El Vergel",
      "El Poblado I",
      "El Poblado II",
      "Los Comuneros Segunda Etapa",
      "Ricardo Balcázar",
      "Omar Torrijos",
      "El Diamante",
      "Lleras Restrepo",
      "Villa del Lago",
      "Los Robles",
      "Rodrigo Lara Bonilla",
      "Charco Azul",
      "Villablanca",
      "Calipso",
      "Yira Castro",
      "Lleras Restrepo II Etapa",
      "Marroquín III",
      "Los Lagos",
      "Sector Laguna del Pondaje",
      "El Pondaje",
      "Sector Asprosocial-Diamante"
    ],
    "Comuna 14": [
      "Alfonso Bonilla Aragón",
      "Alirio Mora Beltrán",
      "Manuela Beltrán",
      "Las Orquídeas",
      "José Manuel Marroquín Segunda Etapa",
      "José Manuel Marroquín Primera Etapa",
      "Puerta del Sol",
      "Los Naranjos I",
      "Promociones Populares B",
      "Los Naranjos II"
    ],
    "Comuna 15": [
      "El Retiro",
      "Comuneros I",
      "Laureano Gómez",
      "El Vallado",
      "Ciudad Córdoba",
      "Mojica",
      "El Morichal",
      "Llano Verde"
    ],
    "Comuna 16": [
      "Mariano Ramos",
      "República de Israel",
      "Unión de Vivienda Popular",
      "Antonio Nariño",
      "Brisas del Limonar",
      "Vendimia",
      "Ciudad 2000",
      "La Alborada"
    ],
    "Comuna 17": [
      "La Playa",
      "Primero de Mayo",
      "Ciudadela Comfandi",
      "Ciudad Universitaria",
      "Caney",
      "Valle del Lili",
      "Santa Anita - La Selva",
      "El Ingenio",
      "Mayapán - Las Vegas",
      "Las Quintas de Don Simón",
      "Ciudad Capri",
      "La Hacienda",
      "Los Portales - Nuevo Rey",
      "Cañaverales - Los Samanes",
      "El Limonar",
      "Bosques del Limonar",
      "El Gran Limonar - Cataya",
      "El Gran Limonar",
      "Unicentro Cali",
      "Ciudadela Pasoancho",
      "Prados del Limonar",
      "Urbanización San Joaquín"
    ],
    "Comuna 18": [
      "Buenos Aires",
      "Barrio Caldas",
      "Los Chorros",
      "Meléndez",
      "Los Farallones",
      "Francisco Eladio Ramírez",
      "Prados del Sur",
      "Horizontes",
      "Mario Correa Rengifo",
      "Lourdes",
      "Colinas del Sur",
      "Alférez Real",
      "Nápoles",
      "El Jordán",
      "Cuarteles Nápoles",
      "Sector Alto de Los Chorros",
      "Polvorines",
      "Sector Meléndez",
      "Sector Alto Jordán",
      "Alto Nápoles"
    ],
    "Comuna 19": [
  "El Refugio",
  "La Cascada",
  "El Lido",
  "Urbanización Tequendama",
  "Barrio Eucarístico",
  "San Fernando Nuevo",
  "Urbanización Nueva Granada",
  "Santa Isabel",
  "Bellavista",
  "San Fernando Viejo",
  "Miraflores",
  "El Cedro",
  "Colseguros Andes",
  "Colseguros",
  "Cristales",
  "Altos de Miraflores",
  "Urbanización La Flora de Cristales",
  "Terrazas de Cristales",
  "Alameda"
],
    "Comuna 20": [
      "Belén",
      "Belisario Caicedo",
      "Brisas de Mayo",
      "Lleras Camargo",
      "Pueblo Joven",
      "La Sultana",
      "Siloé",
      "Tierra Blanca",
      "Urbanización Venezuela",
      "Urbanización Cañaveralejo",
      "Urbanización Cortijo",
      "La Nave",
      "La Estrella",
      "San Francisco",
      "Cortijo",
      "Villa Catalina",
      "Las Cañas"
    ],
    "Comuna 21": [
      "El Remanso",
      "Calimio Desepaz",
      "Potrero Grande",
      "Pizamos I",
      "Pizamos II",
      "Pizamos III - Las Dalias",
      "Manantial de Comfandi",
      "Villamercedes I - Villa Luz - Las Garzas",
      "Compartir",
      "Ciudadela del Río CVC",
      "Ciudad Talanga",
      "Los Líderes",
      "Desepaz - Invicali",
      "Valle Grande",
      "Planta de Tratamiento"
    ],
    "Comuna 22": [
      "Ciudad Jardín",
      "Altos de Ciudad de Jardín",
      "Bochalema",
      "Vivero Parque Residencial",
      "Parcelaciones Pance",
      "Urbanización Río Lili",
      "Alférez Real",
      "Ciudad Campestre",
      "Ciudad Pacífica",
      "Hacienda Kachipay",
      "Bosques del Valle",
      "El Castillo",
      "Encanto del Valle",
      "Tierra Linda",
      "Cañasgordas",
      "El Retiro",
      "La María",
      "La Bocha"
    ]
  


}
   
  